project:
  type: website

website:
  title: "Datos Fiscalia"
  google-analytics: "G-P6YZKK0X3P"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: data/violencia-domestica-2025/index.qmd
      - href: data/delitos-por-robo-2025/index.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



